version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: pokeca_discord_api
    container_name: pokeca_discord_api
    environment:
      EDITOR: vim
      RUBYOPT: '-W:no-deprecated'
      RAILS_ENV: development
    command: /bin/sh -c "bundle && rm -f /api/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e development"
    volumes:
      - ./api:/api:cached
      - api-data-store:/bundle

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    image: pokeca_discord_bot
    container_name: pokeca_discord_bot
    environment:
      EDITOR: vim
      RUBYOPT: '-W:no-deprecated'
    command: /bin/sh -c "bundle exec ruby bot.rb"
    volumes:
      - ./bot:/bot:cached
      - bot-data-store:/bundle

volumes:
  api-data-store:
    driver: local
  bot-data-store:
    driver: local